apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpsoknad-mottak
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  envFrom:
    - configmap: loginservice-idporten
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  liveness:
      path: /api/actuator/health/liveness
      initialDelay: 60
  readiness:
      path: /api/actuator/health/readiness
      initialDelay: 60
  prometheus:
      enabled: true
      path: /api/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 250m
        memory: 1536Mi
