no.nav:
    security:
        jwt:
            client:
                registration:
                    fpinfo:
                        well-known-url: ${token.x.well.known.url}
                        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
                        authentication:
                            client-id: ${token.x.client.id}
                            client-jwk: ${token.x.private.jwk}
                            client-auth-method: private_key_jwt
                        token-exchange:
                            audience: prod-fss:teamforeldrepenger:fpinfo
            issuer:
                selvbetjening:
                    discoveryurl: ${loginservice.idporten.discovery.url}
                    accepted_audience: ${loginservice.idporten.audience}
                    cookie_name: selvbetjening-idtoken

spring:
    config.import: vault://
    cloud:
      vault:
         reactive:
           enabled: false
         enabled: true
         uri: https://vault.adeo.no
         authentication: KUBERNETES
         kubernetes:
            role: fpsoknad-mottak
            kubernetes-path: kubernetes/prod/fss
            service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
         kv:
            enabled: true
            backend: kv/prod/fss
            application-name: fpsoknad-mottak/teamforeldrepenger
            default-context: fpsoknad-mottak/teamforeldrepenger
