management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      enabled: false
server:
  port: 9001
spring:
  mvc:
    log-request-details : true
no.nav:
  security:
    jwt:
      client:
        registration:
          fpfordel:
            token-exchange:
              audience: lokal
          fpoversikt:
            token-exchange:
              audience: lokal
fppdfgen:
  enabled: false
fpfordel:
  base-uri: ${fpfordel.override.url}
  fpfordel-max: ${fpfordel.max}
fpoversikt:
  base-uri: ${fpoversikt.override.url}
