mottak:
   sender:
      domainevent:
         enabled : false

management:

    endpoints:
      web:
        exposure:
          include:  '*'
    endpoint:
        health:
          enabled: false
          show-details : always

varsel:
    queue-name: DEV.QUEUE.1
    hostname: localhost
    port: 1414
    name: QM1
    channelname: DEV.APP.SVRCONN

fppdfgen:
    enabled: false

no.nav:
    security:
      oidc:
        issuer:
          selvbetjening:
            discoveryurl: http://metadata
            accepted_audience: aud-localhost
            cookie_name: localhost-idtoken

sts:
  base-uri: http://www.vg.no

server:
  port: 9001
spring:
  mvc:
    log-request-details : true
