management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      enabled: false
server:
  port: 9001
spring:
  cloud:
    vault:
      enabled: false
  mvc:
    log-request-details : true
  kafka:
    bootstrap-servers: localhost:9093
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${kafka.username}" password="${kafka.password}";
arbeidsforhold:
  base-uri: http://localhost:8060/rest/aareg-services/api
organisasjon:
  base-uri: http://localhost:8060/rest/ereg/api/v2
sts:
  base-uri: http://localhost:8060
pdl:
  base-uri: http://localhost:8060/rest/api/pdl/graphql
fppdfgen:
  enabled: false
kontonummer:
  base-uri: http://localhost:8060/rest/dummy/oppslag
kontoregister:
  base-uri: http://localhost:8060/rest/dummy/oppslag
fpfordel:
  base-uri: http://localhost:8090/fpfordel
digdir:
  base-uri: http://localhost:8060/rest/api/digdir
kafka:
  username: vtp
  password: vtp
mottak:
  sender:
    domainevent:
      enabled: false
no.nav:
  security:
    jwt:
      client:
        registration:
          fpfordel:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            token-exchange:
              audience: local:teamforeldrepenger:fpfordel
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
          pdl-api:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            token-exchange:
              audience: local:teamforeldrepenger:pdl-api
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
          aareg-services:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            token-exchange:
              audience: local:arbeidsforhold:aareg-services-nais
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
          digdir-krr-proxy:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            token-exchange:
              audience: local:arbeidsforhold:digdir-krr-proxy
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
          sokos-kontoregister-person: # TODO: Legg inn i application.yml
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            token-exchange:
              audience: local:okonomi:sokos-kontoregister-person
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
              client-auth-method: private_key_jwt
          localhost:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            token-exchange:
              audience: lokal
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
              client-auth-method: private_key_jwt
          client-credentials-pdl:
            token-endpoint-url: http://localhost:8060/rest/AzureAd/aadb2b/oauth2/v2.0/token
            grant-type: client_credentials
            scope: api://lokal.pdl.pdl-api/.default
            authentication:
              client-id: lokal:teamforeldrepenger:fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
              client-auth-method: private_key_jwt
      issuer:
        tokenx:
          discovery-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
          accepted-audience: lokal
