spring:
  config.import: vault://
  cloud:
    vault:
      reactive:
        enabled: false
      enabled: true
      uri: https://vault.adeo.no
      authentication: KUBERNETES
      kubernetes:
        role: fpsoknad-mottak
        kubernetes-path: kubernetes/prod/fss
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kv:
        enabled: true
        backend: kv/prod/fss
        application-name: fpsoknad-mottak/teamforeldrepenger
        default-context: fpsoknad-mottak/teamforeldrepenger
  kafka:
    properties:
      basic:
        auth:
          user:
            info: ${kafka.schema.registry.user}:${kafka.schema.registry.password}
          credentials:
            source: USER_INFO
      schema:
        registry:
          url: ${kafka.schema.registry}
      endpoint:
        identification:
          algorithm: ''
    security:
      protocol: SSL
    ssl:
      trust-store-location: file:${kafka.truststore.path}
      trust-store-type: JKS
      trust-store-password: ${kafka.credstore.password}
      key-store-location: file:${kafka.keystore.path}
      key-store-type: PKCS12
      key-store-password: ${kafka.credstore.password}
no.nav:
  security:
    jwt:
      client:
        registration:
          fpinfo:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpinfo
          fpfordel:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpfordel
          pdl-api:
            token-exchange:
              audience: prod-fss:pdl:pdl-api
          aareg-services:
            token-exchange:
              audience: prod-fss:arbeidsforhold:aareg-services-nais
          digdir-krr-proxy:
            token-exchange:
              audience: prod-gcp:team-rocket:digdir-krr-proxy
          client-credentials-pdl:
            scope: api://prod-fss.pdl.pdl-api/.default
          sokos-kontoregister-person:
            token-exchange:
              audience: prod-gcp:okonomi:sokos-kontoregister-person
kontoregister:
  enabled: false
