management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      enabled: false
server:
  port: 9001
spring:
  cloud:
    vault:
      enabled: false
  mvc:
    log-request-details : true
  kafka:
    consumer:
      enable-auto-commit: false
      bootstrap-servers: ${bootstrap.servers}
    producer:
      bootstrap-servers: ${bootstrap.servers}


no.nav:
  security:
    jwt:
      client:
        registration:
          fpsoknad-oppslag:
            token-exchange:
              audience: lokal
          fpfordel:
            token-exchange:
              audience: lokal
          fpinfo:
            token-exchange:
              audience: lokal
          pdl-api:
            token-exchange:
              audience: lokal
          aareg-services:
            token-exchange:
              audience: lokal
          digdir-krr-proxy:
            token-exchange:
              audience: lokal
arbeidsforhold:
  base-uri: ${aareg.rs.url}
organisasjon:
  base-uri: ${organisasjon.rs.base.url}
sts:
  base-uri: ${oidc.sts.issuer.url}
fppdfgen:
  enabled: false
pdl:
  base-uri: ${pdl.graphql.base.url}
kontonummer:
  base-uri: ${oppslag.url}
fpfordel:
  base-uri: ${fpfordel.base.url}
digdir:
  base-uri: ${digdir.base.url}
innsyn:
  base-uri: ${fpinfo.base.url}

mottak:
  sender:
    domainevent:
      enabled : false # Konsumeres av fpinfo-historikk ifm meldinger for dittnav
