management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      enabled: false
server:
  port: 9001
spring:
  cloud:
    vault:
      enabled: false
  mvc:
    log-request-details : true
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${kafka.username}" password="${kafka.password}";
no.nav:
  security:
    jwt:
      client:
        registration:
          fpfordel:
            token-exchange:
              audience: lokal
          fpinfo:
            token-exchange:
              audience: lokal
          pdl-api:
            token-exchange:
              audience: lokal
          aareg-services:
            token-exchange:
              audience: lokal
          digdir-krr-proxy:
            token-exchange:
              audience: lokal
          client-credentials-pdl:
            scope: ${pdl.scopes}
          sokos-kontoregister-person: # TODO: Legg inn i application.yml
            token-exchange:
              audience: lokal
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
arbeidsforhold:
  base-uri: ${aareg.rs.url}
organisasjon:
  base-uri: ${organisasjon.rs.base.url}
sts:
  base-uri: ${oidc.sts.issuer.url}
fppdfgen:
  enabled: false
pdl:
  base-uri: ${pdl.graphql.base.url}
kontonummer:
  base-uri: ${oppslag.url}
kontoregister:
  base-uri: ${oppslag.url}
fpfordel:
  base-uri: ${fpfordel.override.url}
digdir:
  base-uri: ${digdir.base.url}
innsyn:
  base-uri: ${fpinfo.override.url}

mottak:
  sender:
    domainevent:
      enabled : true # Konsumeres av fpinfo-historikk ifm meldinger for dittnav
      topic: ${kafka.innsendinghendelse.topic}
