management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      enabled: false
server:
  port: 9001
spring:
  mvc:
    log-request-details : true
fppdfgen:
  enabled: false
fpfordel:
  base-uri: http://localhost:8090/fpfordel
oversikt:
  base-uri: http://localhost:8889
no.nav:
  security:
    jwt:
      client:
        registration:
          fpfordel:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            token-exchange:
              audience: local:teamforeldrepenger:fpfordel
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
          fpoversikt:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            token-exchange:
              audience: local:teamforeldrepenger:fpoversikt
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
          localhost:
            well-known-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            token-exchange:
              audience: lokal
            authentication:
              client-id: fpsoknad-mottak
              client-jwk: src/test/resources/tokenx/jwk.json
              client-auth-method: private_key_jwt
      issuer:
        tokenx:
          discovery-url: http://localhost:8060/rest/tokenx/.well-known/oauth-authorization-server
          accepted-audience: lokal
