no.nav:
  security:
    jwt:
      client:
        registration:
          fpfordel:
            token-exchange:
              audience: prod-fss:teamforeldrepenger:fpfordel
          fpoversikt:
            token-exchange:
              audience: prod-gcp:teamforeldrepenger:fpoversikt
