arbeidsforhold:
    base-uri: http://localhost:8060/rest/aareg-services/api

organisasjon:
    base-uri: http://localhost:8060/rest/ereg/api/v1/organisasjon

sts:
    base-uri: http://localhost:8060
    username: vtp
    password: vtp

sak:
    securitytokenservice:
        username: vtp
        password : vtp
        url: http://localhost:8060/soap/SecurityTokenServiceProvider/
    saker:
        url: http://localhost:8060/rest/sak/api/v1/saker

securitytokenservice:
    username: vtp
    password : vtp
    url: http://localhost:8060/soap/SecurityTokenServiceProvider/

varsel:
    username: username
    enabled: false

mottak:
   sender:
      domainevent:
         enabled : false

no.nav:
    security:
        jwt:
            client:
                registration:
                    fpsoknad-oppslag:
                        well-known-url: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
                        token-exchange:
                            audience: local:teamforeldrepenger:fpsoknad-oppslag
                        authentication:
                            client-id: fpsoknad-mottak
                            client-jwk: src/test/resources/tokenx/jwk.json
                    fpinfo:
                        well-known-url: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
                        token-exchange:
                            audience: local:teamforeldrepenger:fpinfo
                        authentication:
                            client-id: fpsoknad-mottak
                            client-jwk: src/test/resources/tokenx/jwk.json
                    fpfordel:
                        well-known-url: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
                        token-exchange:
                            audience: local:teamforeldrepenger:fpfordel
                        authentication:
                            client-id: fpsoknad-mottak
                            client-jwk: src/test/resources/tokenx/jwk.json
                    pdl-api:
                        well-known-url: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
                        token-exchange:
                            audience: local:teamforeldrepenger:pdl-api
                        authentication:
                            client-id: fpsoknad-mottak
                            client-jwk: src/test/resources/tokenx/jwk.json
            issuer:
                tokenx:
                    discovery-url: http://localhost:8060/rest/v1/sts/.well-known/openid-configuration
                    accepted-audience: fpsoknad-mottak
                selvbetjening:
                    discovery-url: http://localhost:8060/rest/AzureAd/aadb2c/v2.0/.well-known/openid-configuration
                    accepted-audience: OIDC

http.proxy:

management:
    endpoints:
      web:
        exposure:
          include:  '*'
    endpoint:
        health:
          enabled: false
          show-details : always

kafka:
    username: vtp
    password: vtp

server:
    port: 9001
spring:
    cloud:
        vault:
            enabled: false
    mvc:
        log-request-details : true
    kafka:
        consumer:
            enable-auto-commit: false
            bootstrap-servers: localhost:9093
        producer:
            bootstrap-servers: localhost:9093

pdl:
    base-uri: http://localhost:8060/rest/api/pdl/graphql
fppdfgen:
    enabled: false
kontonummer:
    base-uri: http://localhost:8060/rest/dummy/oppslag
fpfordel:
    base-uri: http://localhost:8090/fpfordel
dkif:
    base-uri: http://localhost:8060/rest/api
innsyn:
    base-uri: http://localhost:8040
