mottak:
   sender:
      domainevent:
         enabled : false

management:

    endpoints:
      web:
        exposure:
          include:  '*'
    endpoint:
        health:
          enabled: false
          show-details : always

varsel:
   username: username
   enabled: false
   uri: mq://b27apvl176.preprod.local:1413/MQ1LSC02
   channelname: Q1_FPSOKNAD_VARSEL
   queue-name: QA.Q1_VARSELPRODUKSJON.SEND_VARSEL

kafka:
  username: username
  password: password

pdl:
 base-uri: http://localhost:9001/api/graphql
fppdfgen:
    enabled: false

no.nav:
    security:
      oidc:
        issuer:
          selvbetjening:
            discoveryurl: http://metadata
            accepted_audience: aud-localhost
            cookie_name: localhost-idtoken

sts:
  base-uri: http://www.vg.no

server:
  port: 9001
spring:
  mvc:
    log-request-details : true
