arbeidsforhold:
    base-uri: ${aareg.rs.url}

organisasjon:
    base-uri: ${organisasjon.rs.url}

sts:
    base-uri: ${oidc.sts.issuer.url}
    username: ${kafka.username}
    password: ${kafka.password}

sak:
    securitytokenservice:
        username: ${securitytokenservice.username}
        password : ${securitytokenservice.password}
        url: ${securitytokenservice.url}
    saker:
        url: ${sak.rs.url}

securitytokenservice:
    username: ${kafka.username}
    password : ${kafka.password}
    url: ${securitytokenservice.url}

varsel:
    username: username
    enabled: false

mottak:
   sender:
      domainevent:
         enabled : false

http.proxy:

management:
    endpoints:
      web:
        exposure:
          include:  '*'
    endpoint:
        health:
          enabled: false
          show-details : always

kafka:
    username: ${kafka.username}
    password : ${kafka.password}

server:
    port: 9001
spring:
    cloud:
        vault:
            enabled: false
    mvc:
        log-request-details : true
    kafka:
        consumer:
            enable-auto-commit: false
            bootstrap-servers: ${bootstrap.servers}
        producer:
            bootstrap-servers: ${bootstrap.servers}

pdl:
    base-uri: ${pdl.graphql.base.url}
fppdfgen:
    enabled: false
kontonummer:
    base-uri: ${oppslag.url}
fpfordel:
    base-uri: ${fpfordel.base.url}
dkif:
    base-uri: ${dkif.base.url}
innsyn:
    base-uri: ${fpinfo.base.url}
