package no.nav.foreldrepenger.mottak.innsending.foreldrepenger;

public enum SøknadType {
    INITIELL_FORELDREPENGER, ETTERSENDING_FORELDREPENGER, ENDRING_FORELDREPENGER, INITIELL_ENGANGSSTØNAD, INITIELL_ENGANGSSTØNAD_DOKMOT, UKJENT
}
