apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpsoknad-mottak
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: foreldrepengesoknad-api
          cluster: {{ cluster_foreldrepengesoknad-api }}
    # Outbound rules gjelder bare GCP clusters.
  image: {{image}}
  port: 8080
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
  liveness:
    path: /api/actuator/health/liveness
    initialDelay: 15
  readiness:
    path: /api/actuator/health/readiness
    initialDelay: 15
  prometheus:
    enabled: true
    path: /api/actuator/prometheus
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  secureLogs:
    enabled: true
