apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpsoknad-mottak
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: fpinfo-historikk
        - application: foreldrepengesoknad-api
          cluster: {{ cluster_foreldrepengesoknad-api }}
    # Outbound rules gjelder bare GCP clusters.
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 3
  liveness:
    path: /api/actuator/health/liveness
    initialDelay: 60
  readiness:
    path: /api/actuator/health/readiness
    initialDelay: 60
  prometheus:
    enabled: true
    path: /api/actuator/prometheus
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  resources:
    limits:
      cpu: 1500m
      memory: 3072Mi
    requests:
      cpu: 25m
      memory: 1024Mi
  secureLogs:
    enabled: true
