name: Deployment pipeline q1

on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: x-access-token
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      
            
      - name: Sjekk ut kode
        uses: actions/checkout@v2
        
      - name: Lint Code Base
        uses: github/super-linter@v2.0.0    
     
      - name: Hent tag    
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)"  
             
      - name: Hent Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
  
      - name: Sett opp Java 14      
        uses: actions/setup-java@v1
        with:
          java-version: 14
    
      - name: Kompiler
        run: | 
          echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG" 
          mvn clean install --batch-mode --quiet --settings .github/workflows/.m2/settings.xml
                   
      - name: Bygg, tag og push Docker image  
        run: |
          docker build --tag ${IMAGE} --tag ${IMAGE_BASE}:latest .
          echo  ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE_BASE}   

      - name: Lukk gamle bygg-issues
        if: success()
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['bygg']
            }).then(response => {
              response.data.forEach(issue => {
                github.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              });
            });
            
      - name: Opprett deployment issue
        if: success()
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: createdeployissue
        with:
          labels: 'bygg'
          token: ${{ secrets.NOTIFICATION }}
          title: Deploy av ${{ env.TAG }}
          body: |
            Kommenter med <b>/promote cluster</b>, hvor <b>cluster</b> er <i>dev-fss</i> eller <i>prod-fss</i>
            
      - name: Trigg deploy til dev-fss
        if: success()
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.NOTIFICATION}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ steps.createdeployissue.outputs.number }} }
            github.issues.createComment({...issue,
                                    title: 'Bygg av ${{ env.TAG }}',
                                    body: '/promote dev-fss'})
