name: Build PR or branch

on:
  pull_request:
    branches:
      - master
env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Sett opp Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          check-latest: true
          cache: 'maven'

      - name: Kompiler
        run: |
          mvn package  --settings .github/.m2/settings.xml
