name: Build PR or branch

on:
  pull_request:
    branches:
      - master

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true
          cache: 'maven'

      - name: Kompiler
        run: |
          mvn install -e --batch-mode --settings .github/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
