name: Build PR or branch

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          check-latest: true
          cache: 'maven'

      - name: Kompiler uten sonar
        run: |
          mvn jacoco:prepare-agent install jacoco:report -e --batch-mode --settings .github/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        if: github.actor != 'dependabot[bot]'
        with:
          name: jacoco-report
          path: target/jacoco.exec

  sonar:
    if: github.actor != 'dependabot[bot]'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: jacoco-report
          path: target/jacoco.exec

      - name: Kompiler med sonar
        run: |
          mvn sonar:sonar --settings .github/.m2/settings.xml -Dsonar.login=${SONAR_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

