name: Build PR or branch

on:
  pull_request:
    branches:
      - master
env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Hent Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Sett opp Java 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Kompiler
        run: |
          mvn package  --settings .github/workflows/.m2/settings.xml
