name: Bygg og deploy
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - '.java-version'
      - 'LICENCE'
      - 'CODEOWNERS'

jobs:
  build-app:
    name: Build
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-no-db.yml@main
    with:
      sonar-scan: true
      build-image: ${{ github.ref_name == 'master' }} # default: true
      push-image: ${{ github.ref_name == 'master' }} # default: false
    secrets: inherit

  codeql:
    name: CodeQl
    uses: navikt/fp-gha-workflows/.github/workflows/codeql.yml@main
    secrets: inherit

  autotest:
    name: Autotest
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-autotest/.github/workflows/autotest.yml@autotester
    with:
      build-version: ${{ needs.build-app.outputs.build-version }}
    secrets: inherit

  deploy-dev:
    name: Deploy dev
    if: github.ref_name == 'master'
    needs: [build-app, autotest]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy-app.yml@deploy
    with:
      image: ghcr.io/${{ github.repository }}:${{ needs.build-app.outputs.build-version }}
      cluster: dev-fss
    secrets: inherit

  deploy-prod:
    name: Deploy prod
    if: github.ref_name == 'master'
    needs: [build-app, autotest, deploy-dev]
    uses: navikt/fp-gha-workflows/.github/workflows/deploy-app.yml@deploy
    with:
      image: ghcr.io/${{ github.repository }}:${{ needs.build-app.outputs.build-version }}
      cluster: prod-fss
    secrets: inherit
