name: Build PR or branch

on:
  pull_request:
    branches:
      - master

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          check-latest: true
          cache: 'maven'

      - name: Kompiler
        run: |
          mvn -B install --settings .github/.m2/settings.xml org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=navikt_fpsoknad-mottak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
